name: Release

on:
  push:
    tags:
      - "v2.*"

jobs:
  publish:
    name: Publish NPM

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Configure NPM
        env:
          TOKEN: ${{ secrets.ARTIFACTORY_CLOUD_AUTH }} 
        run: |
          echo "@ciscodesignsystems:registry=https://artifactory.devhub-cloud.cisco.com/artifactory/api/npm/magnetic-common-npm/"  >> .npmrc
          echo "//artifactory.devhub-cloud.cisco.com/artifactory/api/npm/magnetic-common-npm/:_auth=$TOKEN"  >> .npmrc
          echo "//artifactory.devhub-cloud.cisco.com/artifactory/api/npm/magnetic-common-npm/:always-auth=true"  >> .npmrc
          echo "registry=https://registry.npmjs.org/"  >> .npmrc
      - run: npm ci
      - run: npm run build
      - uses: JS-DevTools/npm-publish@v2
        with:
          registry: https://npm.pkg.github.com/
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest
