name: Update Algolia

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Update Algolia

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: NPM Install
        run: npm ci --ignore-scripts --prefer-offline
      - name: Create env
        run: |
          touch .env
          echo ALGOLIA_APP_ID =${{ secrets.ALGOLIA_APP_ID }} >> .env
          echo ALGOLIA_ADMIN_KEY =${{ secrets.ALGOLIA_ADMIN_KEY }} >> .env
          echo ALGOLIA_INDEX_NAME =${{ secrets.ALGOLIA_INDEX_NAME }} >> .env
      - name: Update Algolia
        run: node ./scripts/algolia
